"""create scheduled lessons

Revision ID: 5caf65dc234b
Revises:
Create Date: 2026-09-06 23:47:52.544075

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5caf65dc234b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    op.create_table(
        "scheduled_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="planned", nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("class_id"), "="),
            (sa.text("tstzrange(starts_at, ends_at, '[)')"), "&&"),
            where=sa.text("status = 'planned'"),
            using="gist",
            name="scheduled_lessons_no_class_overlap",
        ),
        postgresql.ExcludeConstraint(
            (sa.column("teacher_id"), "="),
            (sa.text("tstzrange(starts_at, ends_at, '[)')"), "&&"),
            where=sa.text("status = 'planned'"),
            using="gist",
            name="scheduled_lessons_no_teacher_overlap",
        ),
        sa.CheckConstraint("starts_at < ends_at", name="scheduled_lessons_valid_interval"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scheduled_lessons")
    # ### end Alembic commands ###
