"""add idempotency requests

Revision ID: a6eced7396cf
Revises: 5caf65dc234b
Create Date: 2026-09-13 01:38:53.834894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6eced7396cf"
down_revision: str | Sequence[str] | None = "5caf65dc234b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["scheduled_lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation", "idempotency_key", name="idempotency_requests_operation_key_unique"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("idempotency_requests")
    # ### end Alembic commands ###
