from datetime import date
from typing import Protocol

from schedule_service.domain.lesson import Lesson


class LessonRepository(Protocol):
    async def add(self, lesson: Lesson) -> Lesson: ...
    async def get(self, lesson_id: int) -> Lesson | None: ...
    async def update(self, lesson: Lesson, expected_version: int) -> Lesson | None: ...
    async def cancel(self, lesson: Lesson, expected_version: int) -> Lesson | None: ...
    async def list_planned_for_class_on_day(
        self, *, class_id: int, day: date
    ) -> list[Lesson]: ...
