"""create document tables

Revision ID: 606e06014d53
Revises:
Create Date: 2026-09-21 16:26:44.316081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "606e06014d53"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("object_key", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')",
            name="document_jobs_valid_status",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_task_outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_job_id", sa.UUID(), nullable=False),
        sa.Column(
            "task_name",
            sa.String(),
            server_default="documents.generate_certificate",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_job_id"],
            ["document_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_job_id"),
    )
    op.create_index(
        "document_task_outbox_unpublished_created_at_idx",
        "document_task_outbox",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "document_task_outbox_unpublished_created_at_idx",
        table_name="document_task_outbox",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("document_task_outbox")
    op.drop_table("document_jobs")
    # ### end Alembic commands ###
